2025-03-24T11:38:36.385655Z  INFO main ThreadId(01) redcore: src/main.rs:77: ðŸš€ Server starting on http://127.0.0.1:8080
2025-03-24T11:38:36.416959Z  INFO main ThreadId(01) connect_to_db: redcore::db: src/db.rs:25: âœ… Connected to PostgreSQL (Max connections: 5)
2025-03-24T11:49:44.495939Z  INFO main ThreadId(01) redcore: src/main.rs:74: ðŸš€ Server starting on http://127.0.0.1:8080
2025-03-24T11:49:44.527425Z  INFO main ThreadId(01) connect_to_db: redcore::db: src/db.rs:25: âœ… Connected to PostgreSQL (Max connections: 5)
2025-03-24T11:50:01.277964Z DEBUG actix-rt|system:0|arbiter:0 ThreadId(03) register{user=Json(RegisterRequest { username: "up2", name: "New Usadsfsdfsdfer", email: "newn2e@w.com", phone: "1234sdf5346789", password: "new", roles: ["user"] }) pool=Data(Pool { size: 1, num_idle: 1, is_closed: false, options: PoolOptions { max_connections: 5, min_connections: 0, connect_timeout: 10s, max_lifetime: Some(1800s), idle_timeout: Some(600s), test_before_acquire: true } })}:hash_it: redcore::auth::password: src/auth/password.rs:18: Password hashed successfully
2025-03-24T11:50:01.280258Z ERROR actix-rt|system:0|arbiter:0 ThreadId(03) register{user=Json(RegisterRequest { username: "up2", name: "New Usadsfsdfsdfer", email: "newn2e@w.com", phone: "1234sdf5346789", password: "new", roles: ["user"] }) pool=Data(Pool { size: 1, num_idle: 1, is_closed: false, options: PoolOptions { max_connections: 5, min_connections: 0, connect_timeout: 10s, max_lifetime: Some(1800s), idle_timeout: Some(600s), test_before_acquire: true } })}:create_new_user: redcore::auth::queries: src/auth/queries.rs:46: Failed to create new user: error returned from database: duplicate key value violates unique constraint "users_username_key"
2025-03-24T11:50:01.280338Z ERROR actix-rt|system:0|arbiter:0 ThreadId(03) tracing_actix_web::middleware: /home/lucas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-actix-web-0.7.15/src/middleware.rs:258: Error encountered while processing the incoming HTTP request: DatabaseError("error returned from database: duplicate key value violates unique constraint \"users_username_key\"")
2025-03-24T11:52:21.868832Z  INFO main ThreadId(01) redcore: src/main.rs:74: ðŸš€ Server starting on http://127.0.0.1:8080
2025-03-24T11:52:21.900815Z  INFO main ThreadId(01) connect_to_db: redcore::db: src/db.rs:25: âœ… Connected to PostgreSQL (Max connections: 5)
2025-03-24T12:06:03.056627Z  INFO main ThreadId(01) redcore: src/main.rs:77: ðŸš€ Server starting on http://127.0.0.1:8080
2025-03-24T12:06:03.088928Z  INFO main ThreadId(01) connect_to_db: redcore::db: src/db.rs:25: âœ… Connected to PostgreSQL (Max connections: 5)
2025-03-24T12:06:09.802616Z  INFO actix-rt|system:0|arbiter:0 ThreadId(03) login: redcore::auth::handlers: src/auth/handlers.rs:55: ðŸ”µ Received login request for username: new
2025-03-24T12:06:09.805642Z DEBUG actix-rt|system:0|arbiter:0 ThreadId(03) login:query_password_hash{username="new"}: redcore::auth::queries: src/auth/queries.rs:18: Password hash found for user: new
2025-03-24T12:06:10.067071Z DEBUG actix-rt|system:0|arbiter:0 ThreadId(03) login:verify_password: redcore::auth::password: src/auth/password.rs:37: Password verification failed: invalid password
2025-03-24T12:06:10.067150Z  WARN actix-rt|system:0|arbiter:0 ThreadId(03) login: redcore::auth::handlers: src/auth/handlers.rs:77: ðŸš¨ Password mismatch event="login_failed" username=new reason="password_mismatch"
2025-03-24T12:08:39.427363Z  INFO actix-rt|system:0|arbiter:1 ThreadId(04) login: redcore::auth::handlers: src/auth/handlers.rs:55: ðŸ”µ Received login request for username: up2
2025-03-24T12:08:39.427892Z DEBUG actix-rt|system:0|arbiter:1 ThreadId(04) login:query_password_hash{username="up2"}: redcore::auth::queries: src/auth/queries.rs:18: Password hash found for user: up2
2025-03-24T12:08:39.685991Z DEBUG actix-rt|system:0|arbiter:1 ThreadId(04) login:verify_password: redcore::auth::password: src/auth/password.rs:33: Password verified successfully
2025-03-24T12:08:39.728979Z  INFO actix-rt|system:0|arbiter:1 ThreadId(04) login: redcore::auth::handlers: src/auth/handlers.rs:69: âœ… Login successful event="login_successful" username=up2 user_id=34e1bac8-15d4-457f-972d-20b5dc129bd7
2025-03-24T12:27:40.393570Z  INFO main ThreadId(01) redcore: src/main.rs:82: ðŸš€ Server starting on http://127.0.0.1:8080
2025-03-24T12:27:40.424827Z  INFO main ThreadId(01) connect_to_db: redcore::db: src/db.rs:25: âœ… Connected to PostgreSQL (Max connections: 5)
2025-03-24T12:45:35.579691Z  INFO main ThreadId(01) redcore: src/main.rs:80: ðŸš€ Server starting on http://127.0.0.1:8080
2025-03-24T12:45:35.611388Z  INFO main ThreadId(01) connect_to_db: redcore::db: src/db.rs:25: âœ… Connected to PostgreSQL (Max connections: 5)
